version: "3.9"

services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules_frontend:/app/node_modules
      - /app/.next
    command: >
      sh -c "npm install --legacy-peer-deps && 
             npm run dev -- -H 0.0.0.0 -p 3002"
    environment:
      NEXT_PUBLIC_GRAPHQL_ENDPOINT: http://api:4000/graphql
      NODE_ENV: development
    ports: ["3002:3002"]
    depends_on: [api]
    profiles: ["base"]

  api:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./api:/app
      - ./node_modules_api:/app/node_modules
      - ./secrets:/app/secrets:ro
    command: >
      sh -c "apk add --no-cache python3 make g++ openssl openssl-dev && 
             npm install && 
             npx prisma generate && 
             npm run dev"
    environment:
      DATABASE_URL: mysql://beaver:beaver@mariadb:3306/beaver
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: beaver12345
      NODE_ENV: development
      PORT: 4000
      ACCESS_TOKEN_EXPIRY: 30m
      REFRESH_TOKEN_EXPIRY: 8h
    depends_on: [neo4j, mariadb]
    ports: ["4000:4000"]
    profiles: ["base"]

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: beaver
      MARIADB_USER: beaver
      MARIADB_PASSWORD: beaver
    volumes: 
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: ["3306:3306"]
    profiles: ["base"]

  neo4j:
    image: neo4j:5-enterprise
    environment:
      NEO4J_AUTH: neo4j/beaver12345
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4J_dbms_security_auth__minimum__password__length: 8
    volumes: 
      - neo4j-data:/data
      - ./neo4j-init.cypher:/docker-entrypoint-initdb.d/init.cypher
    ports: ["7474:7474", "7687:7687"]
    profiles: ["base"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports: ["9090:9090"]
    profiles: ["observability"]

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    ports: ["3001:3000"]
    profiles: ["observability"]

  loki:
    image: grafana/loki:latest
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    ports: ["3100:3100"]
    profiles: ["observability"]

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./observability/tempo/tempo-config.yaml:/etc/tempo/tempo-config.yaml
      - tempo-data:/tmp/tempo
    ports: ["3200:3200"]
    profiles: ["observability"]

volumes:
  mariadb-data:
  neo4j-data:
  prometheus-data:
  grafana-data:
  loki-data:
  tempo-data: 