global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:4000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb:3306']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474'] 